wandb_version: 1

activation:
  value: tanh
batch:
  value: 100
dropout_rate:
  value: 0
epoch:
  value: 5
epochs:
  value: 5
layer1_size:
  value: 128
layer2_size:
  value: 64
lr:
  value: 0.015
optimizer:
  value: nadam
